# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-04 20:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belty', '0002_quote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='quote',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='belty.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='other',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='belty.Quote'),
        ),
        migrations.AddField(
            model_name='other',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='belty.User'),
        ),
    ]
