# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-04 21:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belty', '0003_auto_20170504_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='other',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='other',
            name='user',
        ),
        migrations.DeleteModel(
            name='Other',
        ),
    ]
