# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-16 06:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belty', '0005_other'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_likes', to='belty.Quote')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_likes', to='belty.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='other',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='other',
            name='user',
        ),
        migrations.DeleteModel(
            name='Other',
        ),
    ]
